// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PostableRESTfulApi.Data;

#nullable disable

namespace PostableRESTFulApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240712013839_LoadLikeData")]
    partial class LoadLikeData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PostableRESTfulApi.Models.Like", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("PostId", "UserId")
                        .IsUnique();

                    b.ToTable("Likes");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8575),
                            PostId = 1,
                            UserId = 4
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8593),
                            PostId = 1,
                            UserId = 6
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8594),
                            PostId = 1,
                            UserId = 8
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8595),
                            PostId = 1,
                            UserId = 9
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8596),
                            PostId = 1,
                            UserId = 10
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8597),
                            PostId = 1,
                            UserId = 11
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8598),
                            PostId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8600),
                            PostId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8602),
                            PostId = 2,
                            UserId = 3
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8603),
                            PostId = 2,
                            UserId = 5
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8604),
                            PostId = 2,
                            UserId = 6
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8605),
                            PostId = 2,
                            UserId = 7
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8606),
                            PostId = 2,
                            UserId = 8
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8607),
                            PostId = 2,
                            UserId = 9
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8608),
                            PostId = 2,
                            UserId = 10
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8609),
                            PostId = 2,
                            UserId = 11
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8610),
                            PostId = 3,
                            UserId = 1
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8611),
                            PostId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8612),
                            PostId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8613),
                            PostId = 3,
                            UserId = 4
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8615),
                            PostId = 3,
                            UserId = 5
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8616),
                            PostId = 3,
                            UserId = 6
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8617),
                            PostId = 3,
                            UserId = 7
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8618),
                            PostId = 3,
                            UserId = 8
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8619),
                            PostId = 3,
                            UserId = 9
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8620),
                            PostId = 3,
                            UserId = 10
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8621),
                            PostId = 3,
                            UserId = 11
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8622),
                            PostId = 4,
                            UserId = 1
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8623),
                            PostId = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8625),
                            PostId = 4,
                            UserId = 3
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8626),
                            PostId = 4,
                            UserId = 4
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8627),
                            PostId = 4,
                            UserId = 5
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8632),
                            PostId = 4,
                            UserId = 6
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8633),
                            PostId = 4,
                            UserId = 7
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8634),
                            PostId = 4,
                            UserId = 8
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8635),
                            PostId = 4,
                            UserId = 9
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8636),
                            PostId = 4,
                            UserId = 10
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8638),
                            PostId = 4,
                            UserId = 11
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8639),
                            PostId = 5,
                            UserId = 1
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8640),
                            PostId = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8641),
                            PostId = 5,
                            UserId = 3
                        },
                        new
                        {
                            Id = 43,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8642),
                            PostId = 5,
                            UserId = 4
                        },
                        new
                        {
                            Id = 44,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8643),
                            PostId = 5,
                            UserId = 5
                        },
                        new
                        {
                            Id = 45,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8644),
                            PostId = 5,
                            UserId = 6
                        },
                        new
                        {
                            Id = 46,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8645),
                            PostId = 5,
                            UserId = 7
                        },
                        new
                        {
                            Id = 47,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8646),
                            PostId = 5,
                            UserId = 8
                        },
                        new
                        {
                            Id = 48,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8648),
                            PostId = 5,
                            UserId = 9
                        },
                        new
                        {
                            Id = 49,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8649),
                            PostId = 5,
                            UserId = 10
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8650),
                            PostId = 5,
                            UserId = 11
                        },
                        new
                        {
                            Id = 51,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8651),
                            PostId = 6,
                            UserId = 1
                        },
                        new
                        {
                            Id = 52,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8652),
                            PostId = 6,
                            UserId = 2
                        },
                        new
                        {
                            Id = 53,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8653),
                            PostId = 6,
                            UserId = 3
                        },
                        new
                        {
                            Id = 54,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8654),
                            PostId = 6,
                            UserId = 4
                        },
                        new
                        {
                            Id = 55,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8655),
                            PostId = 6,
                            UserId = 5
                        },
                        new
                        {
                            Id = 56,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8656),
                            PostId = 6,
                            UserId = 6
                        },
                        new
                        {
                            Id = 57,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8657),
                            PostId = 6,
                            UserId = 7
                        },
                        new
                        {
                            Id = 58,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8659),
                            PostId = 6,
                            UserId = 8
                        },
                        new
                        {
                            Id = 59,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8660),
                            PostId = 6,
                            UserId = 9
                        },
                        new
                        {
                            Id = 60,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8661),
                            PostId = 6,
                            UserId = 10
                        },
                        new
                        {
                            Id = 61,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8663),
                            PostId = 6,
                            UserId = 11
                        },
                        new
                        {
                            Id = 62,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8664),
                            PostId = 7,
                            UserId = 1
                        },
                        new
                        {
                            Id = 63,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8665),
                            PostId = 7,
                            UserId = 2
                        },
                        new
                        {
                            Id = 64,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8666),
                            PostId = 7,
                            UserId = 3
                        },
                        new
                        {
                            Id = 65,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8667),
                            PostId = 7,
                            UserId = 4
                        },
                        new
                        {
                            Id = 66,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8668),
                            PostId = 7,
                            UserId = 5
                        },
                        new
                        {
                            Id = 67,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8669),
                            PostId = 7,
                            UserId = 6
                        },
                        new
                        {
                            Id = 68,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8670),
                            PostId = 7,
                            UserId = 7
                        },
                        new
                        {
                            Id = 69,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8672),
                            PostId = 7,
                            UserId = 8
                        },
                        new
                        {
                            Id = 70,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8673),
                            PostId = 7,
                            UserId = 9
                        },
                        new
                        {
                            Id = 71,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8674),
                            PostId = 7,
                            UserId = 10
                        },
                        new
                        {
                            Id = 72,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8675),
                            PostId = 7,
                            UserId = 11
                        },
                        new
                        {
                            Id = 73,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8676),
                            PostId = 8,
                            UserId = 1
                        },
                        new
                        {
                            Id = 74,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8677),
                            PostId = 8,
                            UserId = 2
                        },
                        new
                        {
                            Id = 75,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8678),
                            PostId = 8,
                            UserId = 3
                        },
                        new
                        {
                            Id = 76,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8679),
                            PostId = 8,
                            UserId = 4
                        },
                        new
                        {
                            Id = 77,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8680),
                            PostId = 8,
                            UserId = 5
                        },
                        new
                        {
                            Id = 78,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8682),
                            PostId = 8,
                            UserId = 6
                        },
                        new
                        {
                            Id = 79,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8683),
                            PostId = 8,
                            UserId = 7
                        },
                        new
                        {
                            Id = 80,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8684),
                            PostId = 8,
                            UserId = 8
                        },
                        new
                        {
                            Id = 81,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8685),
                            PostId = 8,
                            UserId = 9
                        },
                        new
                        {
                            Id = 82,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8686),
                            PostId = 8,
                            UserId = 10
                        },
                        new
                        {
                            Id = 83,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8688),
                            PostId = 8,
                            UserId = 11
                        },
                        new
                        {
                            Id = 84,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8689),
                            PostId = 9,
                            UserId = 1
                        },
                        new
                        {
                            Id = 85,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8690),
                            PostId = 9,
                            UserId = 2
                        },
                        new
                        {
                            Id = 86,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8691),
                            PostId = 9,
                            UserId = 3
                        },
                        new
                        {
                            Id = 87,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8692),
                            PostId = 9,
                            UserId = 4
                        },
                        new
                        {
                            Id = 88,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8694),
                            PostId = 9,
                            UserId = 5
                        },
                        new
                        {
                            Id = 89,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8695),
                            PostId = 9,
                            UserId = 6
                        },
                        new
                        {
                            Id = 90,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8696),
                            PostId = 9,
                            UserId = 7
                        },
                        new
                        {
                            Id = 91,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8697),
                            PostId = 9,
                            UserId = 8
                        },
                        new
                        {
                            Id = 92,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8698),
                            PostId = 9,
                            UserId = 9
                        },
                        new
                        {
                            Id = 93,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8699),
                            PostId = 9,
                            UserId = 10
                        },
                        new
                        {
                            Id = 94,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8700),
                            PostId = 9,
                            UserId = 11
                        },
                        new
                        {
                            Id = 95,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8701),
                            PostId = 10,
                            UserId = 1
                        },
                        new
                        {
                            Id = 96,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8702),
                            PostId = 10,
                            UserId = 2
                        },
                        new
                        {
                            Id = 97,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8703),
                            PostId = 10,
                            UserId = 3
                        },
                        new
                        {
                            Id = 98,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8704),
                            PostId = 10,
                            UserId = 4
                        },
                        new
                        {
                            Id = 99,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8705),
                            PostId = 10,
                            UserId = 5
                        },
                        new
                        {
                            Id = 100,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8706),
                            PostId = 10,
                            UserId = 6
                        },
                        new
                        {
                            Id = 101,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8707),
                            PostId = 10,
                            UserId = 7
                        },
                        new
                        {
                            Id = 102,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8710),
                            PostId = 10,
                            UserId = 8
                        },
                        new
                        {
                            Id = 103,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8711),
                            PostId = 10,
                            UserId = 9
                        },
                        new
                        {
                            Id = 104,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8712),
                            PostId = 10,
                            UserId = 10
                        },
                        new
                        {
                            Id = 105,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8713),
                            PostId = 10,
                            UserId = 11
                        },
                        new
                        {
                            Id = 106,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8714),
                            PostId = 11,
                            UserId = 1
                        },
                        new
                        {
                            Id = 107,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8715),
                            PostId = 11,
                            UserId = 2
                        },
                        new
                        {
                            Id = 108,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8718),
                            PostId = 11,
                            UserId = 3
                        },
                        new
                        {
                            Id = 109,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8719),
                            PostId = 11,
                            UserId = 4
                        },
                        new
                        {
                            Id = 110,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8720),
                            PostId = 11,
                            UserId = 5
                        },
                        new
                        {
                            Id = 111,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8721),
                            PostId = 11,
                            UserId = 6
                        },
                        new
                        {
                            Id = 112,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8722),
                            PostId = 11,
                            UserId = 7
                        },
                        new
                        {
                            Id = 113,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8723),
                            PostId = 11,
                            UserId = 8
                        },
                        new
                        {
                            Id = 114,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8724),
                            PostId = 11,
                            UserId = 9
                        },
                        new
                        {
                            Id = 115,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8725),
                            PostId = 11,
                            UserId = 10
                        },
                        new
                        {
                            Id = 116,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8726),
                            PostId = 11,
                            UserId = 11
                        },
                        new
                        {
                            Id = 117,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8727),
                            PostId = 12,
                            UserId = 1
                        },
                        new
                        {
                            Id = 118,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8728),
                            PostId = 12,
                            UserId = 2
                        },
                        new
                        {
                            Id = 119,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8729),
                            PostId = 12,
                            UserId = 3
                        },
                        new
                        {
                            Id = 120,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8730),
                            PostId = 12,
                            UserId = 4
                        },
                        new
                        {
                            Id = 121,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8803),
                            PostId = 12,
                            UserId = 5
                        },
                        new
                        {
                            Id = 122,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8805),
                            PostId = 12,
                            UserId = 6
                        },
                        new
                        {
                            Id = 123,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8806),
                            PostId = 12,
                            UserId = 7
                        },
                        new
                        {
                            Id = 124,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8807),
                            PostId = 12,
                            UserId = 8
                        },
                        new
                        {
                            Id = 125,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8808),
                            PostId = 12,
                            UserId = 9
                        },
                        new
                        {
                            Id = 126,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8809),
                            PostId = 12,
                            UserId = 10
                        },
                        new
                        {
                            Id = 127,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8810),
                            PostId = 12,
                            UserId = 11
                        },
                        new
                        {
                            Id = 128,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8812),
                            PostId = 13,
                            UserId = 1
                        },
                        new
                        {
                            Id = 129,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8813),
                            PostId = 13,
                            UserId = 2
                        },
                        new
                        {
                            Id = 130,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8814),
                            PostId = 13,
                            UserId = 3
                        },
                        new
                        {
                            Id = 131,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8815),
                            PostId = 13,
                            UserId = 4
                        },
                        new
                        {
                            Id = 132,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8816),
                            PostId = 13,
                            UserId = 5
                        },
                        new
                        {
                            Id = 133,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8818),
                            PostId = 13,
                            UserId = 6
                        },
                        new
                        {
                            Id = 134,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8819),
                            PostId = 13,
                            UserId = 7
                        },
                        new
                        {
                            Id = 135,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8820),
                            PostId = 13,
                            UserId = 8
                        },
                        new
                        {
                            Id = 136,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8821),
                            PostId = 13,
                            UserId = 9
                        },
                        new
                        {
                            Id = 137,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8822),
                            PostId = 13,
                            UserId = 10
                        },
                        new
                        {
                            Id = 138,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8824),
                            PostId = 13,
                            UserId = 11
                        },
                        new
                        {
                            Id = 139,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8825),
                            PostId = 14,
                            UserId = 1
                        },
                        new
                        {
                            Id = 140,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8826),
                            PostId = 14,
                            UserId = 2
                        },
                        new
                        {
                            Id = 141,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8827),
                            PostId = 14,
                            UserId = 3
                        },
                        new
                        {
                            Id = 142,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8828),
                            PostId = 14,
                            UserId = 4
                        },
                        new
                        {
                            Id = 143,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8829),
                            PostId = 14,
                            UserId = 5
                        },
                        new
                        {
                            Id = 144,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8830),
                            PostId = 14,
                            UserId = 6
                        },
                        new
                        {
                            Id = 145,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8831),
                            PostId = 14,
                            UserId = 7
                        },
                        new
                        {
                            Id = 146,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8832),
                            PostId = 14,
                            UserId = 8
                        },
                        new
                        {
                            Id = 147,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8833),
                            PostId = 14,
                            UserId = 9
                        },
                        new
                        {
                            Id = 148,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8834),
                            PostId = 14,
                            UserId = 10
                        },
                        new
                        {
                            Id = 149,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8836),
                            PostId = 14,
                            UserId = 11
                        },
                        new
                        {
                            Id = 150,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8837),
                            PostId = 15,
                            UserId = 1
                        },
                        new
                        {
                            Id = 151,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8838),
                            PostId = 15,
                            UserId = 2
                        },
                        new
                        {
                            Id = 152,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8839),
                            PostId = 15,
                            UserId = 3
                        },
                        new
                        {
                            Id = 153,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8840),
                            PostId = 15,
                            UserId = 4
                        },
                        new
                        {
                            Id = 154,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8841),
                            PostId = 15,
                            UserId = 5
                        },
                        new
                        {
                            Id = 155,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8842),
                            PostId = 15,
                            UserId = 6
                        },
                        new
                        {
                            Id = 156,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8843),
                            PostId = 15,
                            UserId = 7
                        },
                        new
                        {
                            Id = 157,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8845),
                            PostId = 15,
                            UserId = 8
                        },
                        new
                        {
                            Id = 158,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8846),
                            PostId = 15,
                            UserId = 9
                        },
                        new
                        {
                            Id = 159,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8847),
                            PostId = 15,
                            UserId = 10
                        },
                        new
                        {
                            Id = 160,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 276, DateTimeKind.Local).AddTicks(8849),
                            PostId = 15,
                            UserId = 11
                        });
                });

            modelBuilder.Entity("PostableRESTfulApi.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Post para crear una página web. Bienvenidos!!! en este post veremos los pasos para crear una página web",
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 277, DateTimeKind.Local).AddTicks(4039),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Introducción a C# y .NET. En este post aprenderemos sobre los fundamentos de C# y .NET",
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 277, DateTimeKind.Local).AddTicks(4050),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Content = "Cómo usar Entity Framework Core en tus proyectos. Tutorial paso a paso",
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 277, DateTimeKind.Local).AddTicks(4051),
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Content = "Mejores prácticas en el desarrollo de APIs RESTful",
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 277, DateTimeKind.Local).AddTicks(4052),
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Content = "Conceptos básicos de HTML y CSS",
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 277, DateTimeKind.Local).AddTicks(4053),
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            Content = "Cómo empezar con JavaScript",
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 277, DateTimeKind.Local).AddTicks(4055),
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            Content = "Guía para principiantes sobre React",
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 277, DateTimeKind.Local).AddTicks(4056),
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            Content = "Cómo crear un portafolio en línea",
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 277, DateTimeKind.Local).AddTicks(4057),
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            Content = "Introducción a SQL y bases de datos relacionales",
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 277, DateTimeKind.Local).AddTicks(4058),
                            UserId = 3
                        },
                        new
                        {
                            Id = 10,
                            Content = "Cómo optimizar consultas SQL",
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 277, DateTimeKind.Local).AddTicks(4059),
                            UserId = 3
                        },
                        new
                        {
                            Id = 11,
                            Content = "Manejo de transacciones en SQL Server",
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 277, DateTimeKind.Local).AddTicks(4060),
                            UserId = 3
                        },
                        new
                        {
                            Id = 12,
                            Content = "Diseño de esquemas de base de datos eficientes",
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 277, DateTimeKind.Local).AddTicks(4062),
                            UserId = 3
                        },
                        new
                        {
                            Id = 13,
                            Content = "Conceptos básicos de Python para principiantes",
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 277, DateTimeKind.Local).AddTicks(4063),
                            UserId = 4
                        },
                        new
                        {
                            Id = 14,
                            Content = "Cómo usar pandas para análisis de datos",
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 277, DateTimeKind.Local).AddTicks(4064),
                            UserId = 4
                        },
                        new
                        {
                            Id = 15,
                            Content = "Introducción a la inteligencia artificial con Python",
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 277, DateTimeKind.Local).AddTicks(4065),
                            UserId = 4
                        },
                        new
                        {
                            Id = 16,
                            Content = "Desarrollo de aplicaciones web con Flask",
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 277, DateTimeKind.Local).AddTicks(4066),
                            UserId = 4
                        },
                        new
                        {
                            Id = 17,
                            Content = "Fundamentos de programación orientada a objetos",
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 277, DateTimeKind.Local).AddTicks(4067),
                            UserId = 5
                        },
                        new
                        {
                            Id = 18,
                            Content = "Cómo escribir código limpio y mantenible",
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 277, DateTimeKind.Local).AddTicks(4069),
                            UserId = 5
                        },
                        new
                        {
                            Id = 19,
                            Content = "Introducción a los patrones de diseño",
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 277, DateTimeKind.Local).AddTicks(4070),
                            UserId = 5
                        },
                        new
                        {
                            Id = 20,
                            Content = "Cómo hacer pruebas unitarias en C#",
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 277, DateTimeKind.Local).AddTicks(4071),
                            UserId = 5
                        });
                });

            modelBuilder.Entity("PostableRESTfulApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 277, DateTimeKind.Local).AddTicks(8039),
                            Email = "edi_perales@neelvat.com",
                            FirstName = "Edinson",
                            LastName = "Perales",
                            Password = "123456",
                            Role = "Admin",
                            UserName = "EdinsonPerales"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 277, DateTimeKind.Local).AddTicks(8050),
                            FirstName = "John",
                            LastName = "Doe",
                            Password = "password1",
                            Role = "User",
                            UserName = "JohnDoe"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 277, DateTimeKind.Local).AddTicks(8052),
                            Email = "jane_smith@example.com",
                            Password = "password2",
                            Role = "User",
                            UserName = "JaneSmith"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 277, DateTimeKind.Local).AddTicks(8053),
                            FirstName = "Mike",
                            Password = "password3",
                            Role = "User",
                            UserName = "MikeBrown"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 277, DateTimeKind.Local).AddTicks(8054),
                            LastName = "Connor",
                            Password = "password4",
                            Role = "Admin",
                            UserName = "SaraConnor"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 277, DateTimeKind.Local).AddTicks(8056),
                            Password = "password5",
                            Role = "User",
                            UserName = "TomHanks"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 277, DateTimeKind.Local).AddTicks(8057),
                            Email = "emma_watson@example.com",
                            FirstName = "Emma",
                            LastName = "Watson",
                            Password = "password6",
                            Role = "User",
                            UserName = "EmmaWatson"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 277, DateTimeKind.Local).AddTicks(8059),
                            Email = "robert_downey@example.com",
                            Password = "password7",
                            Role = "User",
                            UserName = "RobertDowney"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 277, DateTimeKind.Local).AddTicks(8060),
                            FirstName = "Chris",
                            Password = "password8",
                            Role = "User",
                            UserName = "ChrisEvans"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 277, DateTimeKind.Local).AddTicks(8061),
                            LastName = "Johansson",
                            Password = "password9",
                            Role = "User",
                            UserName = "ScarlettJohansson"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 7, 11, 20, 38, 38, 277, DateTimeKind.Local).AddTicks(8063),
                            FirstName = "Bruce",
                            LastName = "Wayne",
                            Password = "password10",
                            Role = "User",
                            UserName = "BruceWayne"
                        });
                });

            modelBuilder.Entity("PostableRESTfulApi.Models.Like", b =>
                {
                    b.HasOne("PostableRESTfulApi.Models.Post", "Post")
                        .WithMany("Likes")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("PostableRESTfulApi.Models.User", "User")
                        .WithMany("Likes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PostableRESTfulApi.Models.Post", b =>
                {
                    b.HasOne("PostableRESTfulApi.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PostableRESTfulApi.Models.Post", b =>
                {
                    b.Navigation("Likes");
                });

            modelBuilder.Entity("PostableRESTfulApi.Models.User", b =>
                {
                    b.Navigation("Likes");

                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
